/*
 fijarse despues de agregar un bombero el campo brigadas queda activo
    modificar libre brigada
    completar el siniestro entero (constructor de siniestro)
boton asignar en asignar brigada error
 */
package Vistas;

import javax.swing.ImageIcon;

/**
 *
 * @author Juan
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
        this.setTitle("Bomberos");
        this.setLocationRelativeTo(null);
        //this.setIconImage(new ImageIcon(this.getClass().getResource("/universidadgrupo6/Imagenes/icon.jpg")).getImage()); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmBombero = new javax.swing.JMenu();
        jmFormularioBombero = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jBrigadas = new javax.swing.JMenu();
        jmFormularioBrigadas = new javax.swing.JMenuItem();
        jmListadoBrigadas = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmFormularioCuarteles = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmFormularioSiniestro = new javax.swing.JMenuItem();
        jmAgregarBrigadas = new javax.swing.JMenuItem();
        jmResolverSiniestro = new javax.swing.JMenuItem();
        jmMostrarSiniestro = new javax.swing.JMenuItem();
        jmHistoriaSiniestro = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        Escritorio.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 894, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jmBombero.setBackground(new java.awt.Color(255, 255, 255));
        jmBombero.setText("Bomberos");

        jmFormularioBombero.setBackground(new java.awt.Color(255, 255, 255));
        jmFormularioBombero.setText("Formulario Bombero");
        jmFormularioBombero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFormularioBomberoActionPerformed(evt);
            }
        });
        jmBombero.add(jmFormularioBombero);

        jMenuItem3.setText("Listado de Bomberos X Brigadas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jmBombero.add(jMenuItem3);

        jMenuBar1.add(jmBombero);

        jBrigadas.setBackground(new java.awt.Color(255, 255, 255));
        jBrigadas.setForeground(new java.awt.Color(0, 51, 51));
        jBrigadas.setText("Brigadas");

        jmFormularioBrigadas.setBackground(new java.awt.Color(255, 255, 255));
        jmFormularioBrigadas.setText("Formulario Brigadas");
        jmFormularioBrigadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFormularioBrigadasActionPerformed(evt);
            }
        });
        jBrigadas.add(jmFormularioBrigadas);

        jmListadoBrigadas.setText("Brigadas Libres / Ocupadas");
        jmListadoBrigadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListadoBrigadasActionPerformed(evt);
            }
        });
        jBrigadas.add(jmListadoBrigadas);

        jMenuItem2.setText("Listado de  Brigadas X Cuartel");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jBrigadas.add(jMenuItem2);

        jMenuBar1.add(jBrigadas);

        jMenu3.setBackground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("Cuarteles");

        jmFormularioCuarteles.setBackground(new java.awt.Color(255, 255, 255));
        jmFormularioCuarteles.setText("Formulario Cuarteles");
        jmFormularioCuarteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFormularioCuartelesActionPerformed(evt);
            }
        });
        jMenu3.add(jmFormularioCuarteles);

        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(255, 255, 255));
        jMenu4.setText("Siniestros");

        jmFormularioSiniestro.setBackground(new java.awt.Color(255, 255, 255));
        jmFormularioSiniestro.setText("Formulario Siniestro");
        jmFormularioSiniestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFormularioSiniestroActionPerformed(evt);
            }
        });
        jMenu4.add(jmFormularioSiniestro);

        jmAgregarBrigadas.setText("Asignar Brigadas");
        jmAgregarBrigadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAgregarBrigadasActionPerformed(evt);
            }
        });
        jMenu4.add(jmAgregarBrigadas);

        jmResolverSiniestro.setText("Resolver Siniestro");
        jmResolverSiniestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmResolverSiniestroActionPerformed(evt);
            }
        });
        jMenu4.add(jmResolverSiniestro);

        jmMostrarSiniestro.setText("Mostrar Siniestros entre ayer y hoy");
        jmMostrarSiniestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMostrarSiniestroActionPerformed(evt);
            }
        });
        jMenu4.add(jmMostrarSiniestro);

        jmHistoriaSiniestro.setText("Historial siniestros");
        jmHistoriaSiniestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmHistoriaSiniestroActionPerformed(evt);
            }
        });
        jMenu4.add(jmHistoriaSiniestro);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmFormularioBomberoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFormularioBomberoActionPerformed
        
        Escritorio.removeAll();
        Escritorio.repaint();
        BomberoView bv = new BomberoView();
        bv.setVisible(true);
        Escritorio.add(bv);
        Escritorio.moveToFront(bv);

        
    }//GEN-LAST:event_jmFormularioBomberoActionPerformed

    private void jmFormularioCuartelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFormularioCuartelesActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        CuartelView cv = new CuartelView();
        cv.setVisible(true);
        Escritorio.add(cv);
        Escritorio.moveToFront(cv);

    }//GEN-LAST:event_jmFormularioCuartelesActionPerformed

    private void jmFormularioBrigadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFormularioBrigadasActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        BrigadasView brv = new BrigadasView();
        brv.setVisible(true);
        Escritorio.add(brv);
        Escritorio.moveToFront(brv);
    }//GEN-LAST:event_jmFormularioBrigadasActionPerformed

    private void jmFormularioSiniestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFormularioSiniestroActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        SiniestroView sv = new SiniestroView();
        sv.setVisible(true);
        Escritorio.add(sv);
        Escritorio.moveToFront(sv);
    }//GEN-LAST:event_jmFormularioSiniestroActionPerformed

    private void jmListadoBrigadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListadoBrigadasActionPerformed
       
        Escritorio.removeAll();
        Escritorio.repaint();
        ListadoDeBrigadaView lbv = new ListadoDeBrigadaView();
        lbv.setVisible(true);
        Escritorio.add(lbv);
        Escritorio.moveToFront(lbv);
    }//GEN-LAST:event_jmListadoBrigadasActionPerformed

    private void jmMostrarSiniestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMostrarSiniestroActionPerformed
       
        Escritorio.removeAll();
        Escritorio.repaint();
        SiniestosAyeryHoyView sahv =  new SiniestosAyeryHoyView();
        sahv.setVisible(true);
        Escritorio.add(sahv);
        Escritorio.moveToFront(sahv);
        
        
        
    }//GEN-LAST:event_jmMostrarSiniestroActionPerformed

    private void jmAgregarBrigadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAgregarBrigadasActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        AsignarBrigadasView abv = new AsignarBrigadasView();
        abv.setVisible(true);
        Escritorio.add(abv);
        Escritorio.moveToFront(abv);
    }//GEN-LAST:event_jmAgregarBrigadasActionPerformed

    private void jmResolverSiniestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmResolverSiniestroActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        ResolverSiniestroView rsv= new ResolverSiniestroView();
        rsv.setVisible(true);
        Escritorio.add(rsv);
        Escritorio.moveToFront(rsv);
    }//GEN-LAST:event_jmResolverSiniestroActionPerformed

    private void jmHistoriaSiniestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmHistoriaSiniestroActionPerformed
     
        Escritorio.removeAll();
        Escritorio.repaint();
        HistorialSiniestrosView hsv = new HistorialSiniestrosView();
        hsv.setVisible(true);
        Escritorio.add(hsv);
        Escritorio.moveToFront(hsv);
        
        
        
    }//GEN-LAST:event_jmHistoriaSiniestroActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
     
         Escritorio.removeAll();
        Escritorio.repaint();
        BomberosXBrigadasView bxbv = new BomberosXBrigadasView();
        bxbv.setVisible(true);
        Escritorio.add(bxbv);
        Escritorio.moveToFront(bxbv);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        BrigadasXCuartelView bXC = new BrigadasXCuartelView();
        bXC.setVisible(true);
        Escritorio.add(bXC);
        Escritorio.moveToFront(bXC);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu jBrigadas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jmAgregarBrigadas;
    private javax.swing.JMenu jmBombero;
    private javax.swing.JMenuItem jmFormularioBombero;
    private javax.swing.JMenuItem jmFormularioBrigadas;
    private javax.swing.JMenuItem jmFormularioCuarteles;
    private javax.swing.JMenuItem jmFormularioSiniestro;
    private javax.swing.JMenuItem jmHistoriaSiniestro;
    private javax.swing.JMenuItem jmListadoBrigadas;
    private javax.swing.JMenuItem jmMostrarSiniestro;
    private javax.swing.JMenuItem jmResolverSiniestro;
    // End of variables declaration//GEN-END:variables
}
