/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.BrigadaData;
import AccesoADatos.SiniestroData;
import Entidades.Brigada;
import Entidades.Siniestro;
import java.sql.Time;
import java.time.ZoneId;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan
 */
public class ResolverSiniestroView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ResolverSiniestroView
     */
    public ResolverSiniestroView() {
        initComponents();
        llenarComboBox();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcSiniestros = new javax.swing.JComboBox<>();
        jbSalir = new javax.swing.JButton();
        jbResolver = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jcPuntuacion = new javax.swing.JComboBox<>();
        jdFechaResolucion = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jcMinutos = new javax.swing.JComboBox<>();
        jcHora = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("RESOLUCION DE SINIESTRO");

        jLabel2.setText("Fecha de resolucion");

        jLabel3.setText("Hora Resolucion");

        jcSiniestros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcSiniestrosActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbResolver.setText("Resolver");
        jbResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbResolverActionPerformed(evt);
            }
        });

        jLabel4.setText("Puntuacion");

        jcPuntuacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jcPuntuacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcPuntuacionActionPerformed(evt);
            }
        });

        jdFechaResolucion.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setText("Seleccione Siniestro");

        jcMinutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "00", "15", "30", "45", "" }));

        jcHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdFechaResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcSiniestros, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(219, 219, 219))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jbResolver))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbSalir)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(22, 22, 22)
                        .addComponent(jcHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jcMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jcSiniestros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jdFechaResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbResolver)
                    .addComponent(jbSalir))
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcPuntuacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcPuntuacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcPuntuacionActionPerformed

    private void jcSiniestrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcSiniestrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcSiniestrosActionPerformed

    private void jbResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbResolverActionPerformed
        SiniestroData sd = new SiniestroData();
        ArrayList<Siniestro> siniestros = sd.listarSiniestrosNoResueltosConBrigada();
        Siniestro s = new Siniestro();
        BrigadaData bd = new BrigadaData();
        try {
            s = siniestros.get(jcSiniestros.getSelectedIndex());
            s.setFechaResolucion(jdFechaResolucion.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
            Time t = new Time(Integer.parseInt(jcHora.getSelectedItem().toString()), Integer.parseInt(jcMinutos.getSelectedItem().toString()), 00);
            s.setHoraResolucion(t);
            s.setPuntuacion(Integer.parseInt(jcPuntuacion.getSelectedItem().toString()));
            s.setEstado(false);             
            sd.resolverSiniestro(s);           
            int c = s.getBrigada().getCodigo();
            Brigada b = bd.buscarBrigada(c);
            b.setLibre(true);
            bd.modificarBrigada(b);            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos");
        }
        
        LimpiarCampos();
    }//GEN-LAST:event_jbResolverActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
           this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed
    
     private void llenarComboBox(){
        SiniestroData sd = new SiniestroData();
         ArrayList<Siniestro> siniestros= sd.listarSiniestrosNoResueltosConBrigada();
         for (Siniestro siniestro : siniestros) {    
            jcSiniestros.addItem(siniestro.toString());
        }
    }
     
    private void LimpiarCampos(){
        jcMinutos.setSelectedIndex(0);
        jcHora.setSelectedIndex(0);
        jcPuntuacion.setSelectedIndex(0);
        jdFechaResolucion.setDate(null);       
        jcSiniestros.removeAllItems();
        llenarComboBox();
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbResolver;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<String> jcHora;
    private javax.swing.JComboBox<String> jcMinutos;
    private javax.swing.JComboBox<String> jcPuntuacion;
    private javax.swing.JComboBox<String> jcSiniestros;
    private com.toedter.calendar.JDateChooser jdFechaResolucion;
    // End of variables declaration//GEN-END:variables
}
